services:
  helloworld: # 定义服务名称
    image: ghcr.io/sqing33/hello-world # 镜像
    container_name: portainer # 容器名称
    restart: always # 重启策略
    ports:
      - "80:80" # 将主机的80端口映射到容器的80端口
    volumes:
      - (宿主机路径):(容器路径) # 将宿主机路径挂载到容器
    depends_on: # 标识依赖的服务，例如确保 db 启动后再启动h elloworld
      - db
