name: Delete GHCR Images for This Repo

on:
  workflow_dispatch:

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: 删除当前仓库关联的所有 GHCR 镜像
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          echo "Deleting all GHCR images for $OWNER/$REPO ..."

          # 获取所有版本 ID（使用 repos API）
          VERSION_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$OWNER/$REPO/packages/container/$REPO/versions?per_page=100" \
            | jq -r '.[].id')

          if [ -z "$VERSION_IDS" ] || [ "$VERSION_IDS" = "null" ]; then
            echo "❌ 没有找到任何版本，可能是包名不匹配或已经全部删除"
            exit 0
          fi

          for vid in $VERSION_IDS; do
            echo "Deleting version ID: $vid"
            curl -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$OWNER/$REPO/packages/container/$REPO/versions/$vid"
          done

          echo "✅ 删除完成"
