name: Delete GHCR Images Listed in README

on:
  workflow_dispatch:

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 从 README 提取镜像列表
        id: extract
        run: |
          # 提取 <!--SYNC-TABLE-START--> 和 <!--SYNC-TABLE-END--> 之间的内容
          awk '/<!--SYNC-TABLE-START-->/ {flag=1; next} /<!--SYNC-TABLE-END-->/ {flag=0} flag' README.md \
            | tail -n +3 \  # 跳过表头两行
            | awk -F '|' '{print $3}' \
            | sed 's/ //g' \
            | grep -v '^$' > mirrors.txt

          echo "镜像列表："
          cat mirrors.txt

      - name: 删除镜像
        run: |
          while read image; do
            pkg=$(echo "$image" | sed -E 's#ghcr.io/[^/]+/([^:]+):.*#\1#')
            echo "Processing package: $pkg"

            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$pkg/versions?per_page=100")

            # 检查返回值是否为数组
            if ! echo "$RESPONSE" | jq -e 'type=="array"' >/dev/null; then
              echo "  ⚠ API 返回的不是数组，可能没有权限或包不存在"
              echo "  返回内容: $RESPONSE"
              continue
            fi

            VERSION_IDS=$(echo "$RESPONSE" | jq -r '.[].id')

            if [ -z "$VERSION_IDS" ]; then
              echo "  ℹ 没有找到任何版本"
              continue
            fi

            for vid in $VERSION_IDS; do
              echo "  Deleting version ID: $vid"
              curl -s -X DELETE \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$pkg/versions/$vid"
            done
          done < mirrors.txt

          echo "✅ 删除完成"
