name: Delete All GHCR Images for This Repo

on:
  workflow_dispatch:

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: 列出并删除所有镜像
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          echo "Fetching all container packages for $OWNER/$REPO ..."

          # 获取当前仓库的所有容器包
          PACKAGE_NAMES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$OWNER/$REPO/packages?package_type=container&per_page=100" \
            | jq -r '.[].name')

          if [ -z "$PACKAGE_NAMES" ]; then
            echo "❌ 没有找到任何容器包"
            exit 0
          fi

          for pkg in $PACKAGE_NAMES; do
            echo "Processing package: $pkg"
            VERSION_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$OWNER/$REPO/packages/container/$pkg/versions?per_page=100" \
              | jq -r '.[].id')

            for vid in $VERSION_IDS; do
              echo "  Deleting version ID: $vid"
              curl -s -X DELETE \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/$OWNER/$REPO/packages/container/$pkg/versions/$vid"
            done
          done

          echo "✅ 删除完成"
