name: Delete GHCR Images Listed in README

on:
  workflow_dispatch:

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 从 README 提取镜像列表
        id: extract
        run: |
          # 提取 <!--SYNC-TABLE-START--> 和 <!--SYNC-TABLE-END--> 之间的内容
          awk '/<!--SYNC-TABLE-START-->/ {flag=1; next} /<!--SYNC-TABLE-END-->/ {flag=0} flag' README.md \
            | tail -n +3 | awk -F '|' '{print $3}' > /tmp/mirrors.txt

          # 这里取的是“同步后镜像”列（第3列），去掉空行和空格
          sed -i 's/ //g' /tmp/mirrors.txt
          grep -v '^$' /tmp/mirrors.txt > mirrors.txt

          echo "镜像列表："
          cat mirrors.txt

      - name: 删除镜像
        run: |
          while read image; do
            # 从 ghcr.io/username/name:tag 提取包名（去掉 ghcr.io/username/ 前缀和 tag）
            pkg=$(echo "$image" | sed -E 's#ghcr.io/[^/]+/([^:]+):.*#\1#')
            echo "Processing package: $pkg"

            VERSION_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$pkg/versions?per_page=100" \
              | jq -r '.[].id')

            if [ -z "$VERSION_IDS" ] || [ "$VERSION_IDS" = "null" ]; then
              echo "  ⚠ 找不到版本，可能已经删除或无权限"
              continue
            fi

            for vid in $VERSION_IDS; do
              echo "  Deleting version ID: $vid"
              curl -s -X DELETE \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$pkg/versions/$vid"
            done
          done < mirrors.txt

          echo "✅ 删除完成"
