name: Delete All Synced GHCR Images

on:
  workflow_dispatch: # 手动触发

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: 获取镜像列表
        id: list
        run: |
          USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "Fetching package list for $USERNAME..."
          curl -s -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/user/packages/container \
            | jq -r '.[].name' > packages.txt
          echo "PACKAGES=$(cat packages.txt | xargs)" >> $GITHUB_ENV

      - name: 删除所有镜像
        run: |
          USERNAME=$USERNAME
          for pkg in $PACKAGES; do
            echo "Deleting package: $pkg"
            # 获取所有版本 ID
            VERSION_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
              https://api.github.com/user/packages/container/$pkg/versions \
              | jq -r '.[].id')
            for vid in $VERSION_IDS; do
              echo "  Deleting version ID: $vid"
              curl -s -X DELETE \
                -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
                https://api.github.com/user/packages/container/$pkg/versions/$vid
            done
          done
